#!/bin/sh

set -euo pipefail

IMGFILE=${IMGFILE:-/tmp/screen.png}
LOCKER=${LOCKER:-i3lock} # allow different lockers such as `swaylock`
PLAY=0

function takeScreenshot {
  # take the actual screenshot
  scrot $IMGFILE

  # customize scaling to have a pixeled background
  convert $IMGFILE -scale 10% -scale 1000% $IMGFILE
}

function pauseSpotify {
  # playerctl is allowed to fail as it's the fastest way to determine if a player
  # is currently active
  set +e
  rs=$(playerctl status)
  playerctl pause 2> /dev/null
  set -e

  if [ $rs = "Playing" ]; then
    PLAY=1
  fi
}

# locking workflow
pauseSpotify && \
takeScreenshot && \
$LOCKER -i /tmp/screen.png --nofork

if [ $PLAY -eq 1 ]; then
  playerctl play
fi
