#!/bin/sh

IMGFILE=${IMGFILE:-/tmp/screen.png}
LOCKER=${LOCKER:-i3lock} # allow different lockers such as `swaylock`
PLAY=0

function takeScreenshot {
  # take the actual screenshot
  scrot $IMGFILE

  # customize scaling to have a pixeled background
  convert $IMGFILE -scale 10% -scale 1000% $IMGFILE
}

function pauseSpotify {
  # optional feature: playerctl should pause when locking the screen
  # NOTE: the `|| true` is needed since playerctl raises an error if no player is active
  playerctl pause 2> /dev/null
  if [ $? -eq 0 ]; then
    PLAY=1
  fi
}

# locking workflow
pauseSpotify && \
takeScreenshot && \
$LOCKER -i /tmp/screen.png --nofork

if [ $PLAY -eq 1 ]; then
  playerctl play
fi
